### ISSUE TITLE
What's the password?

### ISSUE THREAD

**Issue by LittleRainbow2021** [P3TERX/ssh2actions#1]
Excuse me.
Is "SSH_PASSWORD" the login password?
I couldn't log in successfully.

workflows
```
# This is a basic workflow to help you get started with Actions

name: Debugging with SSH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Start SSH via ngrok
        uses: P3TERX/ssh2actions@main
        with:
          mode: ngrok
        env:
          # After sign up on the https://ngrok.com
          # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

          # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
          # You can find this server region here: https://ngrok.com/docs#global-locations
          NGROK_REGION: us

          # This password you will use when authorizing via SSH
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

          # Send connection info to Telegram (optional)
          # You can find related documents here: https://core.telegram.org/bots
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

```
![image](https://user-images.githubusercontent.com/74524966/99229197-a8291680-2828-11eb-9973-5cb6271b80e9.png)
![image](https://user-images.githubusercontent.com/74524966/99229668-45844a80-2829-11eb-9616-fd176138fbdf.png)
